### ISSUE TITLE
gurobi.sh file is missing

### ISSUE THREAD

**Issue by RaulRC** [tuliotoffolo/fstsp#2]
Hi!

I've been checking your repo for the fstsp problem, but I do not find the gurobi.sh file. Could you kindly upload it?

Thank you in advance.

**Comment by tuliotoffolo** [comment]
Dear Raul,
I unfortunately can’t upload this file. It belongs to Gurobi (see https://www.gurobi.com).

Best regards,
Túlio

Em 22 de jul de 2019 14:10 -0300, Raúl Reguillo Carmona <notifications@github.com>, escreveu:

**Comment by RaulRC** [comment]
Ah thanks! Understood. 

Thanks anyway :D 

Best regards, 

Raúl
