### ISSUE TITLE
murray-fstsp.py não funcionando

### ISSUE THREAD

**Issue by avelin0** [tuliotoffolo/fstsp#3]
Olá, tentei rodar o murray fstsp, mas não estava rodando. 

Primeiro, editei os model.add_constrs para model.add_constr. 

Depois, Editei o mesmo para que os laços for fiquem antes de model.add-constr e deu certo. 

Porém, agora os resultados não estão saindo os mesmos do artigo.

**Comment by avelin0** [comment]
também não estava reconhecendo o BINARY:
```
python3 murray_fstsp.py ../input/OPLInstances/Instance_005.2_new.dat
solutions/murray_Instance_005.2_new.dat.txt
Set parameter Username
Academic license - for non-commercial use only - expires 2025-01-02
Traceback (most recent call last):
  File "/home/avelino/fstsp/fstsp-python/murray_fstsp.py", line 278, in <module>
    formulation = MurrayFormulation(inst)
  File "/home/avelino/fstsp/fstsp-python/murray_fstsp.py", line 25, in __init__
    x = {(i, j): model.add_var(obj=0, var_type=BINARY,
  File "/home/avelino/fstsp/fstsp-python/murray_fstsp.py", line 25, in <dictcomp>
    x = {(i, j): model.add_var(obj=0, var_type=BINARY,
NameError: name 'BINARY' is not defined
```

**Comment by tuliotoffolo** [comment]
Olá @avelin0, tudo bem?
Vou verificar com a Julia e te aviso. Lembro que o código foi re-escrito para o Python-MIP, mas seu relato indica que há algo estranho. 

Aviso assim que tiver uma novidade. 
Abraço!

**Comment by avelin0** [comment]
Tudo bem, obrigado. 

Eu consegui fazer algumas alterações e rodar:

`from mip import BINARY, INTEGER`
 
e colocar os laços for fora das constraints, exemplo:

```
        for i in inst.V_:
            for j in inst.V_:
                for k in inst.V[1:]:
                    if (i, j, k) in inst.D:
                        model.add_constr((2 * y[i, j, k] <= quicksum(x[h, i] for h in inst.V[:-1] if (h, i) in inst.A) + quicksum(x[l, k] for l in inst.V_ if (l, k) in inst.A)), "c9")
```

Mas ainda estou buscando reproduzir o resultado do artigo. segue os dois arquivos com os modelos:

[fstsp-py-murrayfstsp-py.zip](https://github.com/tuliotoffolo/fstsp/files/13837509/fstsp-py-murrayfstsp-py.zip)

**Comment by avelin0** [comment]
Obs: fechei a issue e escondí o comentário anterior sem querer.

Tudo bem, obrigado. 


Eu consegui fazer algumas alterações e rodar:

`from mip import BINARY, INTEGER`
 
e colocar os laços for fora das constraints, exemplo:

```
        for i in inst.V_:
            for j in inst.V_:
                for k in inst.V[1:]:
                    if (i, j, k) in inst.D:
                        model.add_constr((2 * y[i, j, k] <= quicksum(x[h, i] for h in inst.V[:-1] if (h, i) in inst.A) + quicksum(x[l, k] for l in inst.V_ if (l, k) in inst.A)), "c9")
```

Mas ainda estou buscando reproduzir o resultado do artigo. segue os dois arquivos com os modelos:

[fstsp-py-murrayfstsp-py.zip](https://github.com/tuliotoffolo/fstsp/files/13837509/fstsp-py-murrayfstsp-py.zip)
